version: "3.8"

services:
  mysql:
    container_name: quasar-fire_mysql
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: quasar
      MYSQL_USER: root
      MYSQL_PASSWORD: lechuga
      MYSQL_ROOT_PASSWORD: lechuga

volumes:
  mysql_data:
